"""
Abstract Base Strategy — all strategies inherit from this.

Defines the common interface and shared utilities.
"""

from __future__ import annotations

import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Optional

import pandas as pd
import yaml
from loguru import logger


class SignalDirection(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class Signal:
    """A trading signal generated by a strategy."""

    signal_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    strategy: str = ""
    symbol: str = ""
    direction: SignalDirection = SignalDirection.HOLD
    confidence: float = 0.0          # 0 to 1
    score: float = 0.0               # Raw score (strategy-specific)
    price: float = 0.0               # Current price when signal generated
    stop_loss: float = 0.0
    take_profit: float = 0.0
    hold_days: int = 0               # Expected holding period
    regime: str = ""
    features: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)
    notes: str = ""

    @property
    def is_actionable(self) -> bool:
        return self.direction != SignalDirection.HOLD and self.confidence > 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "signal_id": self.signal_id,
            "strategy": self.strategy,
            "symbol": self.symbol,
            "direction": self.direction.value,
            "confidence": self.confidence,
            "score": self.score,
            "price": self.price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "hold_days": self.hold_days,
            "regime": self.regime,
            "features": self.features,
            "datetime": self.timestamp.isoformat(),
            "notes": self.notes,
        }


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Every strategy must implement:
    - generate_signals(): Produce trading signals
    - update(): Process new data
    """

    def __init__(self, name: str, config_path: str = "config/strategies.yaml"):
        self.name = name
        with open(config_path, "r") as f:
            self.all_config = yaml.safe_load(f)

        self.config = self.all_config.get(name, {})
        self.enabled = self.config.get("enabled", True)
        self.weight = self.config.get("weight", 1.0)
        self.active_regimes = self.config.get("active_regimes", [])

        # Performance tracking
        self._signals_history: list[Signal] = []
        self._rolling_returns: list[float] = []
        self._trade_count = 0
        self._win_count = 0

    @abstractmethod
    def generate_signals(self, data: dict[str, Any]) -> list[Signal]:
        """
        Generate trading signals based on current data.

        Args:
            data: Dictionary containing all necessary data for the strategy.
                  Each strategy defines what keys it expects.

        Returns:
            List of Signal objects (can be empty if no signals)
        """
        ...

    @abstractmethod
    def update(self, data: dict[str, Any]) -> None:
        """
        Update strategy state with new data.
        Called on every tick/bar before generate_signals.
        """
        ...

    def is_active_in_regime(self, regime: str) -> bool:
        """Check if this strategy should be active in the given regime."""
        if not self.active_regimes:
            return True  # No regime filter = always active
        return regime in self.active_regimes

    def record_trade_result(self, pnl: float) -> None:
        """Record a trade result for performance tracking."""
        self._rolling_returns.append(pnl)
        self._trade_count += 1
        if pnl > 0:
            self._win_count += 1

        # Keep last 252 trades (1 year)
        if len(self._rolling_returns) > 252:
            self._rolling_returns = self._rolling_returns[-252:]

    @property
    def rolling_sharpe(self) -> float:
        """Calculate rolling Sharpe ratio (risk-free adjusted, 6.5% annual)."""
        if len(self._rolling_returns) < 10:
            return 0.0

        returns = pd.Series(self._rolling_returns[-63:])
        daily_rf = 0.065 / 252  # 6.5% annual risk-free rate
        mean_ret = returns.mean()
        std_ret = returns.std(ddof=1)

        if std_ret == 0 or pd.isna(std_ret):
            return 0.0

        sharpe = (mean_ret - daily_rf) / std_ret * (252 ** 0.5)
        return float(sharpe)

    @property
    def win_rate(self) -> float:
        if self._trade_count == 0:
            return 0.0
        return self._win_count / self._trade_count

    @property
    def stats(self) -> dict[str, Any]:
        return {
            "strategy": self.name,
            "enabled": self.enabled,
            "weight": self.weight,
            "trade_count": self._trade_count,
            "win_rate": round(self.win_rate, 3),
            "rolling_sharpe": round(self.rolling_sharpe, 3),
            "signals_generated": len(self._signals_history),
        }

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}(name={self.name}, enabled={self.enabled})>"
